name: Deploy Site

on:
  push:
    branches: [ hugo ]
  pull_request:
    branches: [ hugo ]
  schedule:
    - cron: '25 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: sudo apt-get install graphicsmagick
    - name: Build
      env:
        GITHUB_WIKI_URL: 'https://github.com/yuzu-emu/yuzu.wiki.git'
        TENANT: 'yuzu'
      run: ./.ci/build.sh
    - name: Deploy
      if: ${{ ! github.base_ref }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: build
        CLEAN: true
        SINGLE_COMMIT: true
